version: '3.8'

services:
  scheduler-service:
    build: .
    env_file:
      - .env
    environment:
      - AWS_REGION=ap-south-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # Optional: Override other environment variables here
      # - KAFKA_URL=kafka:9092
    depends_on:
      - kafka
      - zookeeper
      # Uncomment to use localstack for AWS services
      # - localstack
    networks:
      - ticketly-network

  # Kafka for Debezium events
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - ticketly-network
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ticketly-network

  # Uncomment to use localstack for local AWS development
  # localstack:
  #   image: localstack/localstack:latest
  #   ports:
  #     - "4566:4566"
  #   environment:
  #     - SERVICES=sqs
  #     - DEBUG=1
  #     - AWS_DEFAULT_REGION=ap-south-1
  #   volumes:
  #     - ./localstack:/etc/localstack/init/ready.d
  #   networks:
  #     - ticketly-network

networks:
  ticketly-network:
    driver: bridge